name: Deploy APP em uma EC2 da AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: react-app/package-lock.json

      - name: Run node CI
        run: npm ci
        working-directory: react-app

      - name: Build App
        run: npm run build
        working-directory: react-app

      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: react-app/dist/

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{ vars.AWS_INSTANCE_SG_ID }}
      HOSTNAME: ${{ secrets.SSH_HOST }}
      USER_NAME: ${{ secrets.USER_NAME }}

    steps: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pegar IP do utilizador
        id: get_ip
        run: echo "IP=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

      - name: Adicionar IP do utilizador ao SG
        run: |
            aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr $IP/32 

      - name: Baixar Artefato
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/${{ secrets.SSH_KEY_NAME }}
          chmod 600 ~/.ssh/${{ secrets.SSH_KEY_NAME }}
          ls -la ~/.ssh/

      - name: Esperar SG
        run: sleep 15

      - name: Enviar build
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.SSH_KEY_NAME }}" /home/runner/work/aws-ec2-ci-cd-pipeline/aws-ec2-ci-cd-pipeline/build $USER_NAME@$HOSTNAME:/home/$USER_NAME/react-app

      - name: Enviar build para o Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.SSH_KEY_NAME }} $USER_NAME@$HOSTNAME "sudo cp -r /home/$USER_NAME/react-app/* /var/www/html/"
          
      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.SSH_KEY_NAME }} $USER_NAME@$HOSTNAME "sudo systemctl restart nginx"
        
      - name: Remover IP do utilizador do SG
        if: always()
        run: |
            aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr $IP/32